import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext(null)
const STORAGE_KEY = 'wt_lang'

// พจนานุกรมไทย -> อังกฤษ ของข้อความ UI ที่เขียนโค้ดไว้ตรงๆ เท่านั้น (ปุ่ม/ป้าย/หัวข้อ) — ไม่ใช่ข้อมูลที่ผู้ใช้กรอก/ตั้งค่าเอง
// เช่น ชื่อบริษัท, หมายเหตุ, ตัวเลือกใน picklists ที่ admin เพิ่มเอง ซึ่งแปลอัตโนมัติไม่ได้และคงเป็นภาษาที่กรอกไว้เสมอ
// แปลทีละส่วน — ข้อความที่ยังไม่มีในนี้จะโชว์เป็นภาษาไทยต่อไปตามปกติ (t() คืนค่าเดิมถ้าไม่พบคำแปล ไม่ error)
export const EN_DICT = {
  // ===== Sidebar =====
  'แดชบอร์ด': 'Dashboard',
  'ข้อมูลลูกค้า': 'Customers',
  'บริษัทลูกค้า': 'Companies',
  'ผู้ติดต่อ': 'Contacts',
  'การขาย': 'Sales',
  'ดีลการขาย': 'Deals',
  'ใบเสนอราคา': 'Quotations',
  'ออเดอร์': 'Orders',
  'ข้อมูลสินค้า': 'Products',
  'สินค้า': 'Products',
  'ติดตาม': 'Follow-up',
  'ประวัติการติดต่อ': 'Activity History',
  'งานติดตาม': 'Follow-up Tasks',
  'การเงิน': 'Finance',
  'ตรวจสอบยอดโอน': 'Payment Review',
  'เอกสารบัญชี': 'Accounting Documents',
  'ผู้ดูแลระบบ': 'Admin',
  'ผู้ใช้งาน': 'Users',
  'ผู้ใช้งาน (Users)': 'Users',
  'ออกจากระบบ': 'Log out',
  'ออก': 'Log out',

  // ===== Common buttons/actions =====
  'แก้ไข': 'Edit',
  'ลบ': 'Delete',
  'บันทึก': 'Save',
  'ยกเลิก': 'Cancel',
  'ปิด': 'Close',
  'ยืนยัน': 'Confirm',
  'เพิ่ม': 'Add',
  'ค้นหา...': 'Search...',
  'ค้นหา': 'Search',
  'ส่งออกเป็น Excel': 'Export to Excel',
  'ส่งออกข้อมูล': 'Export',
  'นำเข้าจากไฟล์': 'Import from file',
  'ดูรายละเอียด': 'View details',
  'ดู': 'View',
  'ดู/แก้ไข': 'View/Edit',
  'การจัดการ': 'Actions',
  'สถานะ': 'Status',
  'ทุกสถานะ': 'All statuses',
  'วันที่': 'Date',
  'ถึง': 'to',
  'ล้าง': 'Clear',
  'กำลังโหลด...': 'Loading...',
  'ไม่มีข้อมูล': 'No data',
  'แจ้งเตือน': 'Notifications',
  'บริษัท': 'Company',
  'บริษัท/ผู้ติดต่อ': 'Company/Contact',
  'ลูกค้า': 'Customer',
  'มูลค่า': 'Value',
  'รวม': 'Total',
  'รายการ': 'items',
  'ดีล': 'deals',

  // ===== Dashboard =====
  'ภาพรวมการขาย': 'Sales Overview',
  'ยอดขายรวม': 'Total Sales',
  'จำนวนดีล': 'Number of Deals',
  'บริษัทลูกค้าทั้งหมด': 'Total Companies',
  'ต้องตามเก็บเงิน': 'Payments to Follow Up',
  'Pipeline การขาย': 'Sales Pipeline',

  // ===== Deals =====
  '+ เพิ่มดีล': '+ Add Deal',
  '+ เพิ่ม': '+ Add',
  'ยอดขายที่ปิดดีลสำเร็จ': 'Closed-Won Sales',
  'ยอดที่ต้องติดตาม': 'Amount to Follow Up',
  'รายวัน': 'Daily',
  'รายสัปดาห์': 'Weekly',
  'รายเดือน': 'Monthly',
  'ดีล / สินค้า': 'Deal / Product',
  'จัดการ': 'Actions',
  'ไม่ระบุวันที่': 'No date',
  'ออกใบเสนอราคา': 'Create Quotation',
  'วันที่คาดว่าปิดดีล': 'Expected Close Date',
  'วันที่ต้อง Follow up': 'Follow-up Date',

  // ===== Companies =====
  '+ เพิ่มบริษัท': '+ Add Company',
  'อุตสาหกรรม': 'Industry',
  'เบอร์โทร': 'Phone',
  'อีเมล': 'Email',
  'ประเภทลูกค้า': 'Customer Type',
  'ทุกประเภท': 'All Types',
  'ทุกอุตสาหกรรม': 'All Industries',
  'ชื่อบริษัท': 'Company Name',
  'โทรศัพท์': 'Phone',
  'ผู้รับผิดชอบ': 'Owner',
  'บุคคล': 'Individual',
  'ยังไม่มีข้อมูลบริษัท': 'No companies yet',

  // ===== Dashboard =====
  'บริษัท Active': 'Active Companies',
  'ดีลที่ดำเนินการ': 'Open Deals',
  'ปิดดีลสำเร็จ': 'Closed Won',
  'วันปิด': 'Close Date',
  'งานเกินกำหนด': 'Overdue Tasks',
  'งาน': 'Task',
  'ครบกำหนด': 'Due Date',
  'ลำดับ': 'Priority',
  'ต้องตามเก็บเงิน (ลูกค้าเครดิต)': 'Payments to Follow Up (Credit Customers)',
  'ตั้งแต่': 'From',
  'ไม่มีข้อมูลในช่วงที่เลือก': 'No data in the selected range',
  'กดเพื่อดูรายละเอียด': 'Click for details',
  'Pipeline': 'Pipeline',
  'Top Deals': 'Top Deals',
  'ดูทั้งหมด': 'View all',
  'กิจกรรมล่าสุด': 'Recent Activities',
  'ยังไม่มีกิจกรรม': 'No activities yet',
  'งานที่ต้องทำ (14 วัน)': 'Tasks Due (14 Days)',
  'ไม่มีงานใน 14 วัน': 'No tasks in the next 14 days',
  'ยังไม่มีดีล': 'No deals yet',
  'โดย': 'by',

  // ===== Quotations =====
  '+ สร้างใบเสนอราคา': '+ Create Quotation',
  'เลขที่': 'No.',
  'หัวข้อ': 'Subject',
  'ประเภท': 'Type',
  'ทุกประเภทลูกค้า': 'All Customer Types',
  'ลูกค้าธรรมดา': 'Cash Customer',
  'ลูกค้าเครดิต': 'Credit Customer',
  'คัดลอก': 'Copy',
  'สร้างดีล': 'Create Deal',
  'ธรรมดา': 'Normal',
  'ยังไม่มีใบเสนอราคา': 'No quotations yet',
  'คัดลอกเป็นใบเสนอราคาใหม่': 'Copy as a new quotation',

  // ===== Orders =====
  '+ สร้างออเดอร์': '+ Create Order',
  'สร้างออเดอร์': 'Create Order',
  'เลขที่ออเดอร์': 'Order No.',
  'เลขที่ใบเสนอราคา': 'Quotation No.',
  'เซลล์': 'Sales Rep',
  'วันที่สร้าง': 'Created Date',
  'ใช้งานอยู่': 'Active',
  'ยกเลิกแล้ว': 'Cancelled',
  'ขอตรวจยอด': 'Request Payment Review',
  'เปิดออเดอร์แล้ว': 'Order Opened',
  'เสร็จสิ้น': 'Completed',
  'อัพเดท': 'Updated',
  'ประเภทออเดอร์': 'Order Type',
  'สินค้าปกติ (WT)': 'Normal Goods (WT)',
  'สินค้า Grade B (GB)': 'Grade B Goods (GB)',
  'เลขที่ออเดอร์ (โดยประมาณ)': 'Order No. (estimated)',
  'รายการสินค้า': 'Line Items',
  'สินค้า/รายการ': 'Product/Item',
  'จำนวน': 'Qty',
  'ราคา/หน่วย': 'Unit Price',
  '+ เพิ่มรายการ': '+ Add Item',
  'ที่อยู่จัดส่ง': 'Shipping Address',
  'ที่อยู่สำหรับจัดส่งสินค้า': 'Shipping Address',
  'ชื่อผู้รับ (ถ้ามี)': 'Recipient Name (optional)',
  'เบอร์โทรผู้รับ (ถ้ามี)': 'Recipient Phone (optional)',
  'หมายเหตุ': 'Remark',
  'บันทึกออเดอร์': 'Save Order',
  'เซลล์ผู้เปิดออเดอร์': 'Order Created By',
  'เลขออเดอร์': 'Order No.',
  'เลขใบเสนอราคา': 'Quotation No.',
  'ยอดรวม': 'Total',
  'ยังไม่มีออเดอร์': 'No orders yet',
  'ดูรายละเอียด': 'View details',
  'แสดงเฉพาะใบเสนอราคาที่ยังไม่ถูกใช้เปิดออเดอร์อื่น': 'Only showing quotations not yet used for another order',
  'เลขประจำตัวผู้เสียภาษี': 'Tax ID',
  'ที่อยู่': 'Address',
  'โทร': 'Tel',
  'สินค้า / รายการ': 'Product / Item',
  'ไม่รวม VAT': 'Excl. VAT',
  'รวมทั้งสิ้น': 'Grand Total',
  'เหตุผลที่ยกเลิก': 'Cancellation Reason',
  'เหตุผลที่ยกเลิกออเดอร์': 'Reason for Cancelling Order',
  'ไม่ยกเลิก': "Don't Cancel",
  'ยืนยันยกเลิกออเดอร์': 'Confirm Cancel Order',
  'กำลังยกเลิก...': 'Cancelling...',
  'ยกเลิกออเดอร์': 'Cancel Order',
  'ผู้รับ': 'Recipient',
  'โทรศัพท์บริษัท': 'Company Phone',
  'อีเมลบริษัท': 'Company Email',
  'ที่อยู่บริษัท': 'Company Address',
  'กำลังบันทึก...': 'Saving...',
  'กรุณาระบุเหตุผลที่ยกเลิก': 'Please specify a cancellation reason',

  // ===== Products =====
  'แก้ไขสินค้า': 'Edit Product',
  'เพิ่มสินค้า': 'Add Product',
  'รหัสสินค้า': 'Product Code',
  'ชื่อสินค้า': 'Product Name',
  'รูปสินค้า': 'Product Image',
  'ลบรูป': 'Remove Image',
  'ยังไม่มีสินค้า': 'No products yet',
  'กำลังส่งออก...': 'Exporting...',

  // ===== Contacts (Leads) =====
  '+ เพิ่มผู้ติดต่อ': '+ Add Contact',
  'สรุปตามสถานะ': 'Summary by Status',
  'สรุปตามช่องทางที่มา': 'Summary by Source',
  'ค้นหาชื่อ/เบอร์/อีเมล...': 'Search name/phone/email...',
  'ชื่อ': 'Name',
  'ติดต่อ': 'Contact',
  'ตำแหน่ง/ธุรกิจ': 'Position/Business',
  'สนใจ': 'Interested In',
  'เหตุผล': 'Reason',
  'ที่มา': 'Source',
  'ลูกค้า:': 'Customer:',
  'สร้างเป็นลูกค้า': 'Convert to Customer',
  'ยังไม่มีลีดเข้ามา': 'No contacts yet',

  // ===== Activities =====
  'ประวัติการติดต่อ': 'Activity History',
  '+ บันทึกการติดต่อ': '+ Log Activity',
  'ยังไม่มีการบันทึกกิจกรรม': 'No activities logged yet',
  'วันที่ติดตาม': 'Follow-up Date',
  'ถ้ากรอก ระบบจะสร้างงานติดตามในวันที่นี้ให้อัตโนมัติ ไม่ต้องไปกรอกซ้ำที่หน้างานติดตาม': "If filled in, a follow-up task will be created for this date automatically — no need to re-enter it on the Follow-up Tasks page",

  // ===== Tasks =====
  'งานติดตาม': 'Follow-up Tasks',
  '+ เพิ่มงาน': '+ Add Task',
  'รอดำเนินการ': 'Pending',
  'เกินกำหนด': 'Overdue',
  'ทุกลำดับ': 'All Priorities',
  'วันครบกำหนด': 'Due Date',
  'ไม่มีงาน': 'No tasks',
  'เสร็จ': 'Done',

  // ===== Finance Review =====
  'ตรวจสอบยอดโอน': 'Payment Review',
  'วันที่คำขอ': 'Request Date',
  'ประเภทการชำระ': 'Payment Type',
  'เลขที่ PO': 'PO No.',
  'ยอดไม่รวม VAT': 'Amount Excl. VAT',
  'ยอดรวมทั้งสิ้น': 'Grand Total',
  'ผู้ขอ': 'Requested By',
  'ดูสลิปการโอน': 'View Transfer Slip',
  'ไม่มีสลิปแนบ': 'No slip attached',
  'เทียบยอดโอน/ธนาคาร/วันเวลาจากสลิปจริง': 'Compare amount/bank/time against the actual slip',
  'ไม่มีรายการสินค้า': 'No line items',
  'หมายเหตุจากเซลล์': 'Remark from Sales',
  'ชื่อผู้อนุมัติ (ลายเซ็น)': 'Approver Name (Signature)',
  'ชื่อผู้ตรวจ/อนุมัติ': 'Reviewer/Approver Name',
  'ไม่บังคับ': 'Optional',
  'หมายเหตุจากบัญชี (บังคับกรอก ยกเว้นตอนอนุมัติ)': 'Remark from Finance (required except when approving)',
  'ปฏิเสธ': 'Reject',
  'ยอดไม่ตรง': 'Amount Mismatch',
  'ขอข้อมูลเพิ่ม': 'Request More Info',
  'อนุมัติ': 'Approve',
  'ส่งออกข้อมูล': 'Export',
  'เลขคำขอ': 'Request No.',
  'ไม่มีรายการในสถานะนี้': 'No requests in this status',
  'ตรวจสอบ': 'Review',

  // ===== Accounting Documents =====
  'ทุกความเร่งด่วน': 'All Priorities',
  'ค้นหา ลูกค้า/เซลล์/เลขเอกสาร...': 'Search customer/sales rep/document no...',
  'วันที่ออเดอร์': 'Order Date',
  'ยอดเงิน': 'Amount',
  'ประเภทเอกสาร': 'Document Type',
  'วิธีส่ง': 'Delivery Method',
  'ความเร่งด่วน': 'Priority',
  'อีเมลลูกค้า': 'Customer Email',
  'ส่งตัวจริง': 'Send Original',
  'ใช่': 'Yes',
  'ไม่': 'No',
  'ไม่มีคำขอเอกสารบัญชี': 'No accounting document requests',
  'รายละเอียดคำขอเอกสารบัญชี': 'Accounting Document Request Details',
  'เซลล์ผู้ขอ': 'Requested By',
  'อัพเดทจากเซลล์': 'Updated by Sales',
  'ข้อมูลภาษี': 'Tax Info',
  'ที่อยู่ออกเอกสาร': 'Document Address',
  'อีเมลผู้รับ': 'Recipient Email',
  'ผู้รับเอกสารตัวจริง': 'Original Document Recipient',
  'ที่อยู่จัดส่งตัวจริง': 'Original Shipping Address',
  'หมายเหตุจากเซลล์': 'Remark from Sales',
  'ผลการตรวจสอบ': 'Review Result',
  'ข้อมูลไม่ครบ': 'Missing Info',
  'อัปโหลดเอกสาร (PDF หรือรูปภาพ)': 'Upload Document (PDF or Image)',
  'กำลังอัปโหลด...': 'Uploading...',
  'อัปโหลดเอกสาร': 'Upload Document',
  'ส่งเอกสารตัวจริงแล้ว — ใส่เลข Tracking': 'Original document sent — enter tracking no.',
  'ส่งตัวจริงแล้ว': 'Original Sent',
  'ยกเลิกคำขอ': 'Cancel Request',
  'บันทึกหมายเหตุแล้ว': 'Remark saved',
  'เพิ่มไฟล์เอกสาร (กรณีลูกค้าขอเอกสารหลายอย่าง)': 'Add document file (if customer needs multiple documents)',
  'อัปโหลด': 'Upload',
  '+ เพิ่มไฟล์': '+ Add File',
  'เอกสารที่อัปโหลดแล้ว': 'Uploaded Documents',
  'แก้ไขล่าสุด': 'Last edited',
  'ถ้าข้อมูลไม่ครบ ระบุว่าต้องการอะไรเพิ่ม เช่น ไม่มีเลขผู้เสียภาษี / ที่อยู่ไม่ครบ': "If info is missing, specify what's needed, e.g. no tax ID / incomplete address",
  'ส่งกลับให้เซลล์แก้ไขแล้ว': 'Sent back to sales for correction',
  'อนุมัติแล้ว — อัปโหลดเอกสารได้เลย': 'Approved — you can upload the document now',
  'ออเดอร์นี้ต้องส่งเอกสารตัวจริงด้วย — อัปโหลดแล้วจะไปขั้น "รอส่งตัวจริง"': 'This order also needs the original document sent — after uploading it moves to "Pending Original"',
  'เลข tracking ขนส่ง': 'Courier tracking no.',
  'บันทึก tracking + ปิดงานแล้ว': 'Tracking saved — request closed',
  'ยกเลิกคำขอแล้ว': 'Request cancelled',

  // ===== Users =====
  'พนักงานขาย': 'Sales',
  'ฝ่ายบัญชี': 'Finance',
  'เพิ่มผู้ใช้งานใหม่': 'Add New User',
  'รหัสผ่านเริ่มต้น': 'Initial Password',
  'สุ่มใหม่': 'Regenerate',
  'คัดลอกรหัสผ่านนี้ไปแจ้งพนักงานเอง — ระบบยังไม่มีอีเมลแจ้งอัตโนมัติ': "Copy this password and share it with the employee yourself — there's no automatic email notice yet",
  'สร้างผู้ใช้งาน': 'Create User',
  'แก้ไขผู้ใช้งาน': 'Edit User',
  'รีเซ็ตรหัสผ่านสำเร็จ': 'Password Reset Successful',
  'รหัสผ่านใหม่': 'New Password',
  'คัดลอกรหัสผ่านนี้ไปแจ้งพนักงานเอง — ปิดหน้าต่างนี้แล้วจะดูรหัสผ่านนี้ซ้ำไม่ได้อีก': "Copy this password and share it with the employee yourself — you won't be able to see it again after closing this window",
  'ผู้ใช้งานระบบ': 'System Users',
  'คน': 'people',
  '+ เพิ่มผู้ใช้งาน': '+ Add User',
  'สิทธิ์': 'Role',
  'เข้าร่วมเมื่อ': 'Joined',
  'รีเซ็ตรหัสผ่าน': 'Reset Password',
  'ยังไม่มีผู้ใช้งาน': 'No users yet',
  '(คุณ)': '(You)',
  'ชื่อ-นามสกุล': 'Full Name',

  // ===== Login =====
  'เข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์': 'Sign in with your authorized account',
  'รหัสผ่าน': 'Password',
  'กำลังเข้าสู่ระบบ...': 'Signing in...',
  'เข้าสู่ระบบ': 'Sign In',

  // ===== Company Detail =====
  'ข้อมูลบริษัท': 'Company Info',
  'กิจกรรม': 'Activities',
  'งาน': 'Tasks',
  'ดีล (stat)': 'Deals',
  'เอกสารแนบ': 'Attachments',
  'กลับ': 'Back',
  'เว็บไซต์': 'Website',
  'งานค้าง': 'Pending Tasks',
  'เงื่อนไขเครดิต': 'Credit Term',
  'วันที่สร้าง': 'Created Date',
  'อัปเดตล่าสุด': 'Last Updated',
  'ตำแหน่ง': 'Position',
  'ยังไม่มีผู้ติดต่อ': 'No contacts yet',
  '+ เพิ่ม': '+ Add',
  '+ บันทึก': '+ Log',
  'ยังไม่มีกิจกรรม': 'No activities yet',
  'ยังไม่มีงาน': 'No tasks yet',
  'ครบกำหนดชำระ': 'Payment Due',
  'การชำระ': 'Payment',
  'ยังไม่มีใบเสนอราคา': 'No quotations yet',
  'ไฟล์': 'File',
  'ขนาด': 'Size',
  'อัปโหลดโดย': 'Uploaded By',
  'ดาวน์โหลด': 'Download',
  'ยังไม่มีเอกสารแนบ': 'No attachments yet',
  '+ แนบไฟล์': '+ Attach File',
  'ลบไฟล์นี้?': 'Delete this file?',
  'ชื่อดีล': 'Deal Name',
  'วันปิดดีล': 'Close Date',

  // ===== Modals.jsx (shared) =====
  '-- เลือก --': '-- Select --',
  '-- ไม่ระบุ --': '-- Not specified --',
  'เช่น สมชาย ใจดี': 'e.g. Somchai Jaidee',
  'เช่น สอบถามราคาเครื่องฟอกอากาศ': 'e.g. Inquiry about air purifier price',
  'เอกสาร': 'Document',
  'บันทึก (ฉบับร่าง)': 'Save (Draft)',
  'แก้ไขคำขอ': 'Edit Request',
  'ส่งคำขอที่แก้ไข': 'Resubmit Request',

  // ===== Modals.jsx: Companies =====
  'แก้ไขลูกค้า': 'Edit Customer',
  'เพิ่มลูกค้า': 'Add Customer',
  'ชื่อ-นามสกุลลูกค้า': 'Customer full name',
  'บริษัท ตัวอย่าง จำกัด': 'Example Co., Ltd.',
  'เอกสารแนบ (ภพ20, หนังสือรับรองบริษัท ฯลฯ)': 'Attachments (VAT cert, company registration, etc.)',
  '-- ไม่ใช่ลูกค้าเครดิต (เงินสด) --': '-- Not a credit customer (cash) --',

  // ===== Modals.jsx: Contacts =====
  'แก้ไขผู้ติดต่อ': 'Edit Contact',
  'เพิ่มผู้ติดต่อ': 'Add Contact',
  'แผนก': 'Department',
  'เบอร์โทรศัพท์': 'Phone Number',
  'หัวข้อที่ติดต่อ': 'Contact Subject',
  'เหตุผลในการซื้อ': 'Reason for Purchase',
  'ประเภทธุรกิจ': 'Business Type',
  'ประเภทเครื่องใช้ไฟฟ้าที่สนใจ (เลือกได้หลายข้อ)': 'Appliance Type of Interest (multiple choice)',
  'ระบุประเภทธุรกิจ': 'Specify business type',
  'ระบุเครื่องใช้ไฟฟ้าที่สนใจ': 'Specify appliance of interest',
  'ข้อความเพิ่มเติม': 'Additional Message',

  // ===== Modals.jsx: Deals =====
  'แก้ไขดีล': 'Edit Deal',
  'เพิ่มดีล': 'Add Deal',
  'โปรเจกต์ / สินค้าที่ขาย': 'Project / Product sold',
  'ที่มาของดีล': 'Deal Source',
  '-- ทุกประเภท (เลือกเพื่อกรองรายชื่อบริษัทด้านล่าง) --': '-- All types (select to filter companies below) --',
  'รายการสินค้า (ราคาต่อหน่วยกรอกแบบรวม VAT แล้ว)': 'Line Items (unit price includes VAT)',
  '-- พิมพ์ชื่อสินค้าเพื่อค้นหา หรือพิมพ์ชื่อรายการเอง --': '-- Type a product name to search, or type your own item name --',

  // ===== Modals.jsx: Activities =====
  'บันทึกการติดต่อ': 'Log Activity',
  'ประเภทการติดต่อ': 'Contact Type',
  'สรุปการติดต่อสั้นๆ': 'Brief summary of the contact',
  'บันทึกรายละเอียดการสนทนา...': 'Record the conversation details...',

  // ===== Modals.jsx: Tasks =====
  'แก้ไขงาน': 'Edit Task',
  'เพิ่มงานติดตาม': 'Add Follow-up Task',
  'หัวข้องาน': 'Task Subject',
  'เช่น โทรติดตามใบเสนอราคา': 'e.g. Call to follow up on quotation',
  'ลำดับความสำคัญ': 'Priority Level',

  // ===== Modals.jsx: Quotations =====
  'แก้ไขใบเสนอราคา': 'Edit Quotation',
  'สร้างใบเสนอราคา': 'Create Quotation',
  'ใบเสนอราคาแบบธรรมดา': 'Regular Quotation',
  'จำนวนวันเครดิต': 'Credit Term (Days)',
  'วันครบกำหนดชำระ': 'Payment Due Date',
  'สถานะการชำระ': 'Payment Status',
  'หัวข้อใบเสนอราคา': 'Quotation Subject',
  'ใบเสนอราคาสำหรับ...': 'Quotation for...',
  'วันหมดอายุ': 'Expiry Date',
  'เบอร์ติดต่อเซลล์': 'Sales Contact Number',
  'ชื่อผู้เสนอราคา': 'Proposer Name',
  'ชื่อผู้ออกใบเสนอราคา — พิมพ์ไว้เหนือช่องลงชื่อตอนพิมพ์ ไม่ต้องเซ็นสด': 'Name of the person issuing the quotation — printed above the signature line, no need to sign by hand',

  // ===== AccountingDocModal =====
  'วิธีส่งเอกสาร': 'Delivery Method',
  'ข้อมูลใบกำกับภาษี': 'Tax Invoice Information',
  '(ดึงจากออเดอร์ — แก้ไขได้ก่อนส่ง)': '(auto-filled from the order — editable before submitting)',
  'ชื่อบริษัท/ชื่อลูกค้า': 'Company/Customer Name',
  'สำนักงานใหญ่ / สาขา': 'Head Office / Branch',
  'เลขที่สาขา': 'Branch No.',
  'ที่อยู่สำหรับออกเอกสาร': 'Address for Document Issuance',
  'อีเมลผู้รับเอกสาร': 'Recipient Email',
  'ข้อมูลจัดส่งเอกสารตัวจริง': 'Original Document Shipping Info',
  '(ดึงจากที่อยู่จัดส่งของออเดอร์ — แก้ไขได้)': '(auto-filled from the order shipping address — editable)',
  'ชื่อผู้รับเอกสาร': 'Recipient Name',
  'เบอร์โทรผู้รับเอกสาร': 'Recipient Phone',
  'ที่อยู่จัดส่งเอกสารตัวจริง': 'Original Document Shipping Address',
  'หมายเหตุถึงบัญชี': 'Note to Finance',
  'พรีวิวคำขอ (ให้ลูกค้าเช็คข้อมูล)': 'Request Preview (for customer to verify)',
  'ดาวน์โหลด / พิมพ์': 'Download / Print',
  'ออกในนาม': 'Issued to',
  'เลขผู้เสียภาษี': 'Tax ID',
  'ส่งตัวจริงถึง': 'Original sent to',
  'ต้องการเอกสารบัญชีไหม': 'Do you need accounting documents?',
  'ไม่ต้องการ': 'Not needed',
  'ต้องการ': 'Needed',
  'คำขอเอกสารใหม่': 'New Document Request',
  'ฉบับร่าง — ยังไม่ส่งบัญชี กด "แก้ไข" แล้ว "ส่งคำขอ" เมื่อพร้อม': 'Draft — not yet sent to finance. Click "Edit" then "Submit Request" when ready.',
  'บัญชีแจ้งข้อมูลไม่ครบ': 'Finance reported missing info',
  'หมายเหตุจากบัญชี': 'Remark from Finance',
  'เลขพัสดุ (เอกสารตัวจริง)': 'Tracking No. (Original Document)',
  'กำลังโหลดไฟล์...': 'Loading files...',
  'ยังไม่มีไฟล์ที่บัญชีอัปโหลด': 'No files uploaded by finance yet',
  'ส่งคำขอ': 'Submit Request',
  'กรุณาเลือกประเภทเอกสารก่อนบันทึก': 'Please select a document type before saving',
  'บันทึกฉบับร่างแล้ว (ยังไม่ส่งบัญชี)': 'Draft saved (not yet sent to finance)',
  'กรุณาเลือกประเภทเอกสาร': 'Please select a document type',
  'กรุณาเลือกวิธีส่งเอกสาร': 'Please select a delivery method',
  'ส่งคำขอที่แก้ไขให้บัญชีแล้ว (ขึ้นสถานะอัพเดท)': 'Revised request sent to finance (status updated)',
  'ส่งคำขอเข้าคิวบัญชีแล้ว': 'Request submitted to finance queue',

  // ===== OrderPaymentModal =====
  'ส่วนลด': 'Discount',
  'สลิปการโอน': 'Transfer Slip',
  'มีสลิปแนบอยู่แล้ว (เลือกไฟล์ใหม่เพื่อแทนที่)': 'A slip is already attached (choose a new file to replace it)',
  'ส่งให้บัญชี': 'Submit to Finance',
  'บันทึกฉบับร่างแล้ว': 'Draft saved',
  'ต้องมีรายการสินค้าอย่างน้อย 1 รายการ': 'At least one line item is required',
  'กรุณาแนบสลิปการโอน': 'Please attach the transfer slip',
  'ส่งคำขอให้บัญชีตรวจ? หลังส่งแล้วจะแก้ไขไม่ได้จนกว่าบัญชีจะตีกลับ': 'Submit the request for finance review? Once sent, it cannot be edited until finance sends it back',
  'แจ้งเตือนฝ่ายบัญชีแล้ว': 'Finance has been notified',
  'ส่งคำขอที่แก้ไขให้บัญชีแล้ว': 'Revised request sent to finance',
  'ส่งให้บัญชีตรวจแล้ว': 'Sent to finance for review',
  'บันทึกการเปิดออเดอร์แล้ว': 'Order opening recorded',
  'ยืนยันเปิดออเดอร์': 'Confirm Order Opened',
  'หมายเหตุ (ไม่บังคับ)': 'Remark (optional)',
  'ยังไม่มีสลิปแนบ': 'No slip attached yet',
  'สร้างคำขอตรวจยอด': 'Create Payment Review Request',
  '+ สร้างคำขอตรวจยอด': '+ Create Payment Review Request',
  'ลบสำเร็จ': 'Deleted successfully',
  'เลขที่อนุมัติ': 'Approval No.',
  'ดูสลิป': 'View Slip',
  'ดาวน์โหลด PDF': 'Download PDF',
  'ดาวน์โหลดรูปภาพ': 'Download Image',
  'วิธีการชำระ': 'Payment Method',
  'ระบุวิธีการชำระ': 'Specify payment method',
  'เก็บเงินปลายทาง': 'Cash on Delivery (COD)',
  'เลขที่ Tracking': 'Tracking No.',
  'กรุณาระบุเลขที่ Tracking': 'Please enter the tracking no.',
  'ไม่ต้องแนบสลิป — ลูกค้าเก็บเงินปลายทาง บัญชีจะตรวจสอบยอดเอง': 'No slip needed — customer pays on delivery, accounting will verify the amount directly',
  'ส่วนลดท้ายบิล': 'Bill Discount',
  'เปอร์เซ็นต์': 'Percent',
  'จำนวนเงิน': 'Fixed Amount',

  // ===== Import Modals =====
  'นำเข้าบริษัทลูกค้าจากไฟล์': 'Import Companies from File',
  'นำเข้าผู้ติดต่อจากไฟล์': 'Import Contacts from File',
  'นำเข้าสินค้าจากไฟล์': 'Import Products from File',
  '1) ดาวน์โหลด Template  2) กรอกข้อมูลใน Excel  3) อัปโหลดไฟล์ .xlsx กลับมาที่นี่': '1) Download the template  2) Fill in the data in Excel  3) Upload the .xlsx file back here',
  'ดาวน์โหลด Template (.xlsx)': 'Download Template (.xlsx)',
  'อัปโหลดไฟล์ (.xlsx)': 'Upload File (.xlsx)',
  'ไฟล์:': 'File:',
  'แถวที่': 'Row',
  'ปัญหา': 'Issue',
  'เลือกไฟล์ใหม่': 'Choose a different file',
  'ชื่อบริษัทเหล่านี้มีอยู่แล้วในระบบ — เลือกว่าจะสร้างเป็นรายการใหม่ (ซ้ำชื่อ) หรืออัปเดตทับข้อมูลเดิม ก่อนกดนำเข้า': 'These company names already exist in the system — choose whether to create a new record (duplicate name) or overwrite the existing data before importing',
  'สร้างใหม่ (ซ้ำชื่อ)': 'Create new (duplicate name)',
  'อัปเดตทับข้อมูลเดิม': 'Overwrite existing data',
  'ส่งออกเฉพาะแถวที่มีปัญหา': 'Export problem rows only',
  'กำลังนำเข้า...': 'Importing...',

  // ===== NotificationBell =====
  'การแจ้งเตือน': 'Notifications',
  'อ่านทั้งหมด': 'Mark all read',
  'ไม่มีการแจ้งเตือน': 'No notifications',

  // ===== Reusable Selects (EditableSelect/SearchableSelect) =====
  'แก้ไขตัวเลือก': 'Edit options',
  'ยังไม่มีตัวเลือก': 'No options yet',
  'เพิ่มตัวเลือกใหม่': 'Add new option',
  '-- ไม่เลือก --': '-- Not selected --',
  'ไม่พบสินค้าที่ตรงกัน — จะใช้ข้อความนี้เป็นชื่อรายการที่พิมพ์เอง': 'No matching product found — this text will be used as a custom item name',
  'ไม่พบรายการที่ตรงกัน': 'No matching option found',

  // ===== Pagination =====
  '‹ ก่อนหน้า': '‹ Previous',
  'ถัดไป ›': 'Next ›',

  // ===== SignedQuotationControl =====
  'ไฟล์เซ็นกลับ': 'Signed File',
  'ลบไฟล์เซ็นกลับ': 'Delete Signed File',
  'แนบไฟล์เซ็นกลับ': 'Attach Signed File',
  'ลบไฟล์ใบเสนอราคาที่เซ็นกลับนี้?': 'Delete this signed quotation file?',
  'แนบไฟล์เซ็นกลับสำเร็จ': 'Signed file attached successfully',
  'ลบไฟล์สำเร็จ': 'File deleted successfully',

  // ===== PublicLeadPage =====
  'บริษัท เวิลด์เทค อีเล็คโทรนิค จำกัด': 'Worldtech Electronic Co., Ltd.',
  'ผู้จัดจำหน่ายเครื่องใช้ไฟฟ้าสำหรับธุรกิจและองค์กร': 'Distributor of home appliances for businesses and organizations',
  'ได้รับข้อมูลแล้ว': 'Information received',
  'เซลล์จะติดต่อกลับโดยเร็วที่สุด': 'Our sales team will contact you as soon as possible',
  'ข้อมูลติดต่อ': 'Contact Information',
  'เรื่องที่ต้องการติดต่อ': 'Subject',
  'ข้อมูลเพิ่มเติม (ช่วยให้เซลล์ติดต่อกลับได้ตรงจุดขึ้น)': 'Additional Info (helps our sales team follow up more accurately)',
  'หัวข้อที่ต้องการติดต่อ': 'Subject of Inquiry',
  'ระบุประเภทธุรกิจของคุณ': 'Specify your business type',
  'กรุณากรอกหัวข้อ ชื่อ และเบอร์โทรศัพท์': 'Please fill in the subject, name, and phone number',
  'กรุณาระบุประเภทธุรกิจ': 'Please specify your business type',
  'กรุณาระบุประเภทเครื่องใช้ไฟฟ้าที่สนใจ': 'Please specify the appliance you are interested in',
  'ส่งข้อมูล': 'Submit',
  'กำลังส่ง...': 'Sending...',
  'หรือติดต่อเราโดยตรงทาง LINE:': 'Or contact us directly via LINE:',
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'th' } catch { return 'th' }
  })
  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, lang) } catch { /* noop: private mode ฯลฯ */ }
  }, [lang])

  const t = (th) => (lang === 'en' ? (EN_DICT[th] || th) : th)

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
