import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext(null)
const STORAGE_KEY = 'wt_lang'

// พจนานุกรมไทย -> อังกฤษ ของข้อความ UI ที่เขียนโค้ดไว้ตรงๆ เท่านั้น (ปุ่ม/ป้าย/หัวข้อ) — ไม่ใช่ข้อมูลที่ผู้ใช้กรอก/ตั้งค่าเอง
// เช่น ชื่อบริษัท, หมายเหตุ, ตัวเลือกใน picklists ที่ admin เพิ่มเอง ซึ่งแปลอัตโนมัติไม่ได้และคงเป็นภาษาที่กรอกไว้เสมอ
// แปลทีละส่วน — ข้อความที่ยังไม่มีในนี้จะโชว์เป็นภาษาไทยต่อไปตามปกติ (t() คืนค่าเดิมถ้าไม่พบคำแปล ไม่ error)
export const EN_DICT = {
  // ===== Sidebar =====
  'แดชบอร์ด': 'Dashboard',
  'ข้อมูลลูกค้า': 'Customers',
  'บริษัทลูกค้า': 'Companies',
  'ผู้ติดต่อ': 'Contacts',
  'การขาย': 'Sales',
  'ดีลการขาย': 'Deals',
  'ใบเสนอราคา': 'Quotations',
  'ออเดอร์': 'Orders',
  'ข้อมูลสินค้า': 'Products',
  'สินค้า': 'Products',
  'ติดตาม': 'Follow-up',
  'ประวัติการติดต่อ': 'Activity History',
  'งาน Follow-up': 'Follow-up Tasks',
  'การเงิน': 'Finance',
  'ตรวจสอบยอดโอน': 'Payment Review',
  'เอกสารบัญชี': 'Accounting Documents',
  'ผู้ดูแลระบบ': 'Admin',
  'ผู้ใช้งาน': 'Users',
  'ผู้ใช้งาน (Users)': 'Users',
  'ออกจากระบบ': 'Log out',
  'ออก': 'Log out',

  // ===== Common buttons/actions =====
  'แก้ไข': 'Edit',
  'ลบ': 'Delete',
  'บันทึก': 'Save',
  'ยกเลิก': 'Cancel',
  'ปิด': 'Close',
  'ยืนยัน': 'Confirm',
  'เพิ่ม': 'Add',
  'ค้นหา...': 'Search...',
  'ค้นหา': 'Search',
  'ส่งออกเป็น Excel': 'Export to Excel',
  'ส่งออกข้อมูล': 'Export',
  'นำเข้าจากไฟล์': 'Import from file',
  'ดูรายละเอียด': 'View details',
  'ดู': 'View',
  'ดู/แก้ไข': 'View/Edit',
  'การจัดการ': 'Actions',
  'สถานะ': 'Status',
  'ทุกสถานะ': 'All statuses',
  'วันที่': 'Date',
  'ถึง': 'to',
  'ล้าง': 'Clear',
  'กำลังโหลด...': 'Loading...',
  'ไม่มีข้อมูล': 'No data',
  'แจ้งเตือน': 'Notifications',
  'บริษัท': 'Company',
  'ลูกค้า': 'Customer',
  'มูลค่า': 'Value',
  'รวม': 'Total',
  'รายการ': 'items',
  'ดีล': 'deals',

  // ===== Dashboard =====
  'ภาพรวมการขาย': 'Sales Overview',
  'ยอดขายรวม': 'Total Sales',
  'จำนวนดีล': 'Number of Deals',
  'บริษัทลูกค้าทั้งหมด': 'Total Companies',
  'ต้องตามเก็บเงิน': 'Payments to Follow Up',
  'Pipeline การขาย': 'Sales Pipeline',

  // ===== Deals =====
  '+ เพิ่มดีล': '+ Add Deal',
  '+ เพิ่ม': '+ Add',
  'ยอดขายที่ปิดดีลสำเร็จ': 'Closed-Won Sales',
  'ยอดที่ต้องติดตาม': 'Amount to Follow Up',
  'รายวัน': 'Daily',
  'รายสัปดาห์': 'Weekly',
  'รายเดือน': 'Monthly',
  'ดีล / สินค้า': 'Deal / Product',
  'จัดการ': 'Actions',
  'ไม่ระบุวันที่': 'No date',
  'ออกใบเสนอราคา': 'Create Quotation',
  'วันที่คาดว่าปิดดีล': 'Expected Close Date',
  'วันที่ต้อง Follow up': 'Follow-up Date',

  // ===== Companies =====
  '+ เพิ่มบริษัท': '+ Add Company',
  'อุตสาหกรรม': 'Industry',
  'เบอร์โทร': 'Phone',
  'อีเมล': 'Email',
  'ประเภทลูกค้า': 'Customer Type',
  'ทุกประเภท': 'All Types',
  'ทุกอุตสาหกรรม': 'All Industries',
  'ชื่อบริษัท': 'Company Name',
  'โทรศัพท์': 'Phone',
  'ผู้รับผิดชอบ': 'Owner',
  'บุคคล': 'Individual',
  'ยังไม่มีข้อมูลบริษัท': 'No companies yet',

  // ===== Dashboard =====
  'บริษัท Active': 'Active Companies',
  'ดีลที่ดำเนินการ': 'Open Deals',
  'ปิดดีลสำเร็จ': 'Closed Won',
  'วันปิด': 'Close Date',
  'งานเกินกำหนด': 'Overdue Tasks',
  'งาน': 'Task',
  'ครบกำหนด': 'Due Date',
  'ลำดับ': 'Priority',
  'ต้องตามเก็บเงิน (ลูกค้าเครดิต)': 'Payments to Follow Up (Credit Customers)',
  'ตั้งแต่': 'From',
  'ไม่มีข้อมูลในช่วงที่เลือก': 'No data in the selected range',
  'กดเพื่อดูรายละเอียด': 'Click for details',
  'Pipeline': 'Pipeline',
  'Top Deals': 'Top Deals',
  'ดูทั้งหมด': 'View all',
  'กิจกรรมล่าสุด': 'Recent Activities',
  'ยังไม่มีกิจกรรม': 'No activities yet',
  'งานที่ต้องทำ (14 วัน)': 'Tasks Due (14 Days)',
  'ไม่มีงานใน 14 วัน': 'No tasks in the next 14 days',
  'ยังไม่มีดีล': 'No deals yet',
  'โดย': 'by',

  // ===== Quotations =====
  '+ สร้างใบเสนอราคา': '+ Create Quotation',
  'เลขที่': 'No.',
  'หัวข้อ': 'Subject',
  'ประเภท': 'Type',
  'ทุกประเภทลูกค้า': 'All Customer Types',
  'ลูกค้าธรรมดา': 'Cash Customer',
  'ลูกค้าเครดิต': 'Credit Customer',
  'คัดลอก': 'Copy',
  'สร้างดีล': 'Create Deal',
  'ธรรมดา': 'Normal',
  'ยังไม่มีใบเสนอราคา': 'No quotations yet',
  'คัดลอกเป็นใบเสนอราคาใหม่': 'Copy as a new quotation',

  // ===== Orders =====
  '+ สร้างออเดอร์': '+ Create Order',
  'สร้างออเดอร์': 'Create Order',
  'เลขที่ออเดอร์': 'Order No.',
  'เลขที่ใบเสนอราคา': 'Quotation No.',
  'เซลล์': 'Sales Rep',
  'วันที่สร้าง': 'Created Date',
  'ใช้งานอยู่': 'Active',
  'ยกเลิกแล้ว': 'Cancelled',
  'ขอตรวจยอด': 'Request Payment Review',
  'เปิดออเดอร์แล้ว': 'Order Opened',
  'เสร็จสิ้น': 'Completed',
  'อัพเดท': 'Updated',
  'ประเภทออเดอร์': 'Order Type',
  'สินค้าปกติ (WT)': 'Normal Goods (WT)',
  'สินค้า Grade B (GB)': 'Grade B Goods (GB)',
  'เลขที่ออเดอร์ (โดยประมาณ)': 'Order No. (estimated)',
  'รายการสินค้า': 'Line Items',
  'จำนวน': 'Qty',
  'ราคา/หน่วย': 'Unit Price',
  '+ เพิ่มรายการ': '+ Add Item',
  'ที่อยู่จัดส่ง': 'Shipping Address',
  'ที่อยู่สำหรับจัดส่งสินค้า': 'Shipping Address',
  'ชื่อผู้รับ (ถ้ามี)': 'Recipient Name (optional)',
  'เบอร์โทรผู้รับ (ถ้ามี)': 'Recipient Phone (optional)',
  'หมายเหตุ': 'Remark',
  'บันทึกออเดอร์': 'Save Order',
  'เซลล์ผู้เปิดออเดอร์': 'Order Created By',
  'เลขออเดอร์': 'Order No.',
  'เลขใบเสนอราคา': 'Quotation No.',
  'ยอดรวม': 'Total',
  'ยังไม่มีออเดอร์': 'No orders yet',
  'ดูรายละเอียด': 'View details',
  'แสดงเฉพาะใบเสนอราคาที่ยังไม่ถูกใช้เปิดออเดอร์อื่น': 'Only showing quotations not yet used for another order',
  'เลขประจำตัวผู้เสียภาษี': 'Tax ID',
  'ที่อยู่': 'Address',
  'โทร': 'Tel',
  'สินค้า / รายการ': 'Product / Item',
  'ไม่รวม VAT': 'Excl. VAT',
  'รวมทั้งสิ้น': 'Grand Total',
  'เหตุผลที่ยกเลิก': 'Cancellation Reason',
  'เหตุผลที่ยกเลิกออเดอร์': 'Reason for Cancelling Order',
  'ไม่ยกเลิก': "Don't Cancel",
  'ยืนยันยกเลิกออเดอร์': 'Confirm Cancel Order',
  'กำลังยกเลิก...': 'Cancelling...',
  'ยกเลิกออเดอร์': 'Cancel Order',
  'ผู้รับ': 'Recipient',
  'โทรศัพท์บริษัท': 'Company Phone',
  'อีเมลบริษัท': 'Company Email',
  'ที่อยู่บริษัท': 'Company Address',
  'กำลังบันทึก...': 'Saving...',
  'กรุณาระบุเหตุผลที่ยกเลิก': 'Please specify a cancellation reason',

  // ===== Products =====
  'แก้ไขสินค้า': 'Edit Product',
  'เพิ่มสินค้า': 'Add Product',
  'รหัสสินค้า': 'Product Code',
  'ชื่อสินค้า': 'Product Name',
  'รูปสินค้า': 'Product Image',
  'ลบรูป': 'Remove Image',
  'ยังไม่มีสินค้า': 'No products yet',
  'กำลังส่งออก...': 'Exporting...',

  // ===== Contacts (Leads) =====
  '+ เพิ่มผู้ติดต่อ': '+ Add Contact',
  'สรุปตามสถานะ': 'Summary by Status',
  'สรุปตามช่องทางที่มา': 'Summary by Source',
  'ค้นหาชื่อ/เบอร์/อีเมล...': 'Search name/phone/email...',
  'ชื่อ': 'Name',
  'ติดต่อ': 'Contact',
  'ตำแหน่ง/ธุรกิจ': 'Position/Business',
  'สนใจ': 'Interested In',
  'เหตุผล': 'Reason',
  'ที่มา': 'Source',
  'ลูกค้า:': 'Customer:',
  'สร้างเป็นลูกค้า': 'Convert to Customer',
  'ยังไม่มีลีดเข้ามา': 'No contacts yet',

  // ===== Activities =====
  'ประวัติการติดต่อ': 'Activity History',
  '+ บันทึกการติดต่อ': '+ Log Activity',
  'ยังไม่มีการบันทึกกิจกรรม': 'No activities logged yet',

  // ===== Tasks =====
  'งาน Follow-up': 'Follow-up Tasks',
  '+ เพิ่มงาน': '+ Add Task',
  'รอดำเนินการ': 'Pending',
  'เกินกำหนด': 'Overdue',
  'ทุกลำดับ': 'All Priorities',
  'วันครบกำหนด': 'Due Date',
  'ไม่มีงาน': 'No tasks',
  'เสร็จ': 'Done',

  // ===== Finance Review =====
  'ตรวจสอบยอดโอน': 'Payment Review',
  'วันที่คำขอ': 'Request Date',
  'ประเภทการชำระ': 'Payment Type',
  'เลขที่ PO': 'PO No.',
  'ยอดไม่รวม VAT': 'Amount Excl. VAT',
  'ยอดรวมทั้งสิ้น': 'Grand Total',
  'ผู้ขอ': 'Requested By',
  'ดูสลิปการโอน': 'View Transfer Slip',
  'ไม่มีสลิปแนบ': 'No slip attached',
  'เทียบยอดโอน/ธนาคาร/วันเวลาจากสลิปจริง': 'Compare amount/bank/time against the actual slip',
  'ไม่มีรายการสินค้า': 'No line items',
  'หมายเหตุจากเซลล์': 'Remark from Sales',
  'ชื่อผู้อนุมัติ (ลายเซ็น)': 'Approver Name (Signature)',
  'ชื่อผู้ตรวจ/อนุมัติ': 'Reviewer/Approver Name',
  'ไม่บังคับ': 'Optional',
  'หมายเหตุจากบัญชี (บังคับกรอก ยกเว้นตอนอนุมัติ)': 'Remark from Finance (required except when approving)',
  'ปฏิเสธ': 'Reject',
  'ยอดไม่ตรง': 'Amount Mismatch',
  'ขอข้อมูลเพิ่ม': 'Request More Info',
  'อนุมัติ': 'Approve',
  'ส่งออกข้อมูล': 'Export',
  'เลขคำขอ': 'Request No.',
  'ไม่มีรายการในสถานะนี้': 'No requests in this status',
  'ตรวจสอบ': 'Review',

  // ===== Accounting Documents =====
  'ทุกความเร่งด่วน': 'All Priorities',
  'ค้นหา ลูกค้า/เซลล์/เลขเอกสาร...': 'Search customer/sales rep/document no...',
  'วันที่ออเดอร์': 'Order Date',
  'ยอดเงิน': 'Amount',
  'ประเภทเอกสาร': 'Document Type',
  'วิธีส่ง': 'Delivery Method',
  'ความเร่งด่วน': 'Priority',
  'อีเมลลูกค้า': 'Customer Email',
  'ส่งตัวจริง': 'Send Original',
  'ใช่': 'Yes',
  'ไม่': 'No',
  'ไม่มีคำขอเอกสารบัญชี': 'No accounting document requests',
  'รายละเอียดคำขอเอกสารบัญชี': 'Accounting Document Request Details',
  'เซลล์ผู้ขอ': 'Requested By',
  'อัพเดทจากเซลล์': 'Updated by Sales',
  'ข้อมูลภาษี': 'Tax Info',
  'ที่อยู่ออกเอกสาร': 'Document Address',
  'อีเมลผู้รับ': 'Recipient Email',
  'ผู้รับเอกสารตัวจริง': 'Original Document Recipient',
  'ที่อยู่จัดส่งตัวจริง': 'Original Shipping Address',
  'หมายเหตุจากเซลล์': 'Remark from Sales',
  'ผลการตรวจสอบ': 'Review Result',
  'ข้อมูลไม่ครบ': 'Missing Info',
  'อัปโหลดเอกสาร (PDF หรือรูปภาพ)': 'Upload Document (PDF or Image)',
  'กำลังอัปโหลด...': 'Uploading...',
  'อัปโหลดเอกสาร': 'Upload Document',
  'ส่งเอกสารตัวจริงแล้ว — ใส่เลข Tracking': 'Original document sent — enter tracking no.',
  'ส่งตัวจริงแล้ว': 'Original Sent',
  'ยกเลิกคำขอ': 'Cancel Request',
  'บันทึกหมายเหตุแล้ว': 'Remark saved',
  'เพิ่มไฟล์เอกสาร (กรณีลูกค้าขอเอกสารหลายอย่าง)': 'Add document file (if customer needs multiple documents)',
  'อัปโหลด': 'Upload',
  '+ เพิ่มไฟล์': '+ Add File',
  'เอกสารที่อัปโหลดแล้ว': 'Uploaded Documents',
  'แก้ไขล่าสุด': 'Last edited',
  'ถ้าข้อมูลไม่ครบ ระบุว่าต้องการอะไรเพิ่ม เช่น ไม่มีเลขผู้เสียภาษี / ที่อยู่ไม่ครบ': "If info is missing, specify what's needed, e.g. no tax ID / incomplete address",
  'ส่งกลับให้เซลล์แก้ไขแล้ว': 'Sent back to sales for correction',
  'อนุมัติแล้ว — อัปโหลดเอกสารได้เลย': 'Approved — you can upload the document now',
  'ออเดอร์นี้ต้องส่งเอกสารตัวจริงด้วย — อัปโหลดแล้วจะไปขั้น "รอส่งตัวจริง"': 'This order also needs the original document sent — after uploading it moves to "Pending Original"',
  'เลข tracking ขนส่ง': 'Courier tracking no.',
  'บันทึก tracking + ปิดงานแล้ว': 'Tracking saved — request closed',
  'ยกเลิกคำขอแล้ว': 'Request cancelled',

  // ===== Users =====
  'พนักงานขาย': 'Sales',
  'ฝ่ายบัญชี': 'Finance',
  'เพิ่มผู้ใช้งานใหม่': 'Add New User',
  'รหัสผ่านเริ่มต้น': 'Initial Password',
  'สุ่มใหม่': 'Regenerate',
  'คัดลอกรหัสผ่านนี้ไปแจ้งพนักงานเอง — ระบบยังไม่มีอีเมลแจ้งอัตโนมัติ': "Copy this password and share it with the employee yourself — there's no automatic email notice yet",
  'สร้างผู้ใช้งาน': 'Create User',
  'แก้ไขผู้ใช้งาน': 'Edit User',
  'รีเซ็ตรหัสผ่านสำเร็จ': 'Password Reset Successful',
  'รหัสผ่านใหม่': 'New Password',
  'คัดลอกรหัสผ่านนี้ไปแจ้งพนักงานเอง — ปิดหน้าต่างนี้แล้วจะดูรหัสผ่านนี้ซ้ำไม่ได้อีก': "Copy this password and share it with the employee yourself — you won't be able to see it again after closing this window",
  'ผู้ใช้งานระบบ': 'System Users',
  'คน': 'people',
  '+ เพิ่มผู้ใช้งาน': '+ Add User',
  'สิทธิ์': 'Role',
  'เข้าร่วมเมื่อ': 'Joined',
  'รีเซ็ตรหัสผ่าน': 'Reset Password',
  'ยังไม่มีผู้ใช้งาน': 'No users yet',
  '(คุณ)': '(You)',
  'ชื่อ-นามสกุล': 'Full Name',

  // ===== Login =====
  'เข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์': 'Sign in with your authorized account',
  'รหัสผ่าน': 'Password',
  'กำลังเข้าสู่ระบบ...': 'Signing in...',
  'เข้าสู่ระบบ': 'Sign In',

  // ===== Company Detail =====
  'ข้อมูลบริษัท': 'Company Info',
  'กิจกรรม': 'Activities',
  'งาน': 'Tasks',
  'ดีล (stat)': 'Deals',
  'เอกสารแนบ': 'Attachments',
  'กลับ': 'Back',
  'เว็บไซต์': 'Website',
  'งานค้าง': 'Pending Tasks',
  'เงื่อนไขเครดิต': 'Credit Term',
  'วันที่สร้าง': 'Created Date',
  'อัปเดตล่าสุด': 'Last Updated',
  'ตำแหน่ง': 'Position',
  'ยังไม่มีผู้ติดต่อ': 'No contacts yet',
  '+ เพิ่ม': '+ Add',
  '+ บันทึก': '+ Log',
  'ยังไม่มีกิจกรรม': 'No activities yet',
  'ยังไม่มีงาน': 'No tasks yet',
  'ครบกำหนดชำระ': 'Payment Due',
  'การชำระ': 'Payment',
  'ยังไม่มีใบเสนอราคา': 'No quotations yet',
  'ไฟล์': 'File',
  'ขนาด': 'Size',
  'อัปโหลดโดย': 'Uploaded By',
  'ดาวน์โหลด': 'Download',
  'ยังไม่มีเอกสารแนบ': 'No attachments yet',
  '+ แนบไฟล์': '+ Attach File',
  'ลบไฟล์นี้?': 'Delete this file?',
  'ชื่อดีล': 'Deal Name',
  'วันปิดดีล': 'Close Date',
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'th' } catch { return 'th' }
  })
  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, lang) } catch { /* noop: private mode ฯลฯ */ }
  }, [lang])

  const t = (th) => (lang === 'en' ? (EN_DICT[th] || th) : th)

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
